### PR TITLE
Building-blocks

### PR DESCRIPTION
**Pull request by elyor-doniyorov**
We build blocks using enumerable methods.

### CODE REVIEW

**Comment by elyor-doniyorov** [comment]
Thank you for your reviews! We know we have linter errors that need to be fixed. But we need help to understand them. It says cyclomatic/perceived complexity is too high.

**Review by mke2111 — CHANGES_REQUESTED** [review]
# **STATUS: CHANGES REQUIRED ⚪** 

Hey **@EL28DEV and @uwadonat**, Congratulations 🥇 to you all for your efforts towards this project. It meets all the requirements. Except for the readme file.

- [ ] Add a description on how to run your `b_blocks.rb` enumerable methods.

### Cheers 🍷 

Reach me on slack: **Roy Mukuye**

**Comment by uwadonat** [comment]
Thank you for your helpful review. It helped us to improve our project.

**Comment by uwadonat** [comment]
We added running project instructions to the Readme file.

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Elyor Doniyorov Doniyor & Donat Donat** 
Amazing job with the improvements to your project :muscle:  :muscle:
Your Enumerable methods passes all the tests :clap: :clap: :clap:  
There are just a couple of details to improve before you can go ahead:

- [ ] Don't overuse rubocop disable
- [ ] Fix rubocop offenses
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Comment by elyor-doniyorov** [comment]
Thank you for the review. But we don't see rubocop offenses to be corrected:
Screenshot (310)

Could you please tell us more in detail?

**Comment by elyor-doniyorov** [comment]
After the last review, we updated the rubocop complexity comments and placed in .rubocop.yml file.

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Elyor Doniyorov Doniyor & Donat Donat** 
Nice job introducing the improvements to your project  :muscle:  :muscle: 
Just one last detail:

- [ ] When I run rubocop in the local environment it shows me the next offense:


Please fix this last error for the approval of your project :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Comment by elyor-doniyorov** [comment]
Thanks, Oscar Andrés Russi Porras for your clear feedback. The last offense is fixed.

**Review by GzimAsani — APPROVED** [review]
# **STATUS: APPROVED** 
Congratulations **TEAM**  , Great job implementing the requirements, this project is approved and you can move to your next project 
Don't forget to submit a project completion form.
 Cheers! 👍🏽

<hr>
### if you have any question kindly reach me on slack @GzimAsani

### HAPPY CODING :computer:

**Comment by elyor-doniyorov** [comment]
Thank you!

**Pull request merged**
